# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
      
      - uses: actions/checkout@v2
        
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        
      - name: Clean
        run: rm -rf out
        
      - name: BuildIt
        run: |
          mkdir -p out
          go build -o out/example ./cmd/example
     
      - name: Test
        run: |
          go vet
          go test
        continue-on-error: false
